apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: ${DC_INST_ID}-tutorial
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Mi
