apiVersion: v1
kind: Pod
metadata:
  name: app1
spec:
  containers:
  - name: app1
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done"]
    volumeMounts:
    - name: efs-pv
      mountPath: /data
  volumes:
  - name: efs-pv
    persistentVolumeClaim:
      claimName: efs-claim
